USE master
GO

IF EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = N'SWP_G4')
BEGIN
	ALTER DATABASE SWP_G4 SET OFFLINE WITH ROLLBACK IMMEDIATE;
	ALTER DATABASE SWP_G4 SET ONLINE;
	DROP DATABASE SWP_G4;
END
GO

CREATE DATABASE SWP_G4;
GO

USE SWP_G4
GO

-- 1
CREATE TABLE [User](
UserID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
Username NVARCHAR(60) NOT NULL,
[Password] NVARCHAR(20) NOT NULL,
Email NVARCHAR(200) NOT NULL UNIQUE,
Address VARCHAR(200),
Role VARCHAR(15) DEFAULT 'User',
Phone VARCHAR(11) NOT NULL UNIQUE
);
GO