name: SonarCloud Analysis
on:
  push:
    branches:
      - main
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Hoặc phiên bản Node.js bạn dùng
          cache: 'npm' # Cache node_modules để tăng tốc build
      - name: Install dependencies
        run: npm ci # npm ci nhanh và ổn định hơn npm install cho CI
      - name: Run tests with coverage
        run: npm test -- --coverage --passWithNoTests # --passWithNoTests để workflow không fail nếu không có test nào
      - name: Generate coverage report (nếu cần)
        run: npm run coverage # Nếu bạn có script "coverage" trong package.json
      - name: Run SonarScanner
        run: |
          npx sonarqube-scanner \
            -Dsonar.projectKey=Group-4-SWP-SP25_Group4_SWP_SP25 \
            -Dsonar.organization=group-4-swp-sp25 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.sources=. \
            -Dsonar.exclusions=**/*.test.js,**/__mocks__/**,**/node_modules/** # Loại trừ node_modules
            -Dsonar.tests=__tests__ \
            -Dsonar.test.inclusions=**/*.test.js \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: SonarCloud Quality Gate check (Optional)
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5 # Timeout nếu quality gate check quá lâu
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
